### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by sjagoe**
If actions `exec` returns a non-zero exit code, but doesn't raise an error we should still error the action

### CODE REVIEW

**Review by JohnDing1995 — APPROVED** [review]
LGTM!

**Comment by JohnDing1995** [comment]
> If actions `exec` returns a non-zero exit code, but doesn't raise an error we should still error the action

I guess such a situation considered as a bug in the gha runner?

**Comment by sjagoe** [comment]
> I guess such a situation considered as a bug in the gha runner?

Not the runner, it's behaviour of https://github.com/actions/toolkit/tree/main/packages/exec

But I think the bug is in our code, because that library *can* return non-zero without raising an error, I think. But it's complex code so I don't know the underlying cause

**Review by fisherking — APPROVED** [review]

**Comment by sjagoe** [comment]
I realised what I was doing wrong in my new test, and fixed it to properly await, and assert that all compose calls occur in this case

**Review by fisherking — APPROVED** [review]

**Pull request merged**
